### ISSUE TITLE
(Question) Why is another registry/package manager necessary?

### ISSUE THREAD

**Issue by hulkish** [runtools/run#6]
This is a repost of https://github.com/resdir/resdir/issues/1, as I believe this is probably the more correct place.

**Comment by mvila** [comment]
Thanks, @hulkish, this is actually a very good question! 😄 It gives me the opportunity to talk a bit about [Resdir](https://resdir.com/) which is for me as essential as Run.

First, the [resources](https://run.tools/docs/introduction/what-is-a-resource) are designed to be language agnostic. I started with JavaScript, but, hopefully, more languages will come in the future. So we need to build a language agnostic registry.

Then, and this is the most important, I want to fix two major problems we encounter with npm (and probably all registries).

### Discoverability

Since everyone can publish in npm what they want with any name, it's hard to sort through the good packages and the not so good ones. Here is how I see things with Resdir: everyone can publish what they want in their personal namespace (`aturing/nice-tool`), but to be able to publish in a generic namespace (`js/bundler`, `tool/notifier`, `python/linter`, etc.), you need community approval.

Typically, a resource will start its life in a personal namespace (`aturing/machine`), and later, when it is mature enough, the author will be able to rename it (without breaking references to the original name) using a generic namespace (`computer/machine`). But for that, he will first have to submit his resource to the community. Then after review, the community will be able to approve (maybe with some kind of voting system) the resource. I am aware that this may seem a little heavy, but I believe it is necessary to get a quality directory of resources.

### Security

[This story](https://hackernoon.com/im-harvesting-credit-card-numbers-and-passwords-from-your-site-here-s-how-9a8cb347c5b5) illustrates the problem very well. A resource used by many people cannot depend on a single person. The risk is too high. So, to fix that problem, all new versions published in a generic namespace will have to be approved by a minimum number (two?) of contributors. Again, it sounds heavy, but it's actually what already happens in projects of some importance. Resdir will just enforce this good practice.

It is the first time I've talked about these ideas, and I'd love to hear from you guys.

**Comment by RobertFischer** [comment]
CPAN (perl) has this basic model, which seems to have served it well.

Also, you clearly need to have a blockchain for distributed approvals. :D

**Comment by RobertFischer** [comment]
Thinking about it some more, I actually think you want to base the promotion on usage -- has the project been in use long enough that it's become a cornerstone project, and has it been maintained long enough that the maintainer has demonstrated commitment?

I'd also be inclined to make the promoted packages deploy from a repo that the community controls (eg: `runtools/common-resources`). That prevents a dickish maintainer from taking their ball and going home (eg: the [left-pad unpleasantness](http://www.businessinsider.com/npm-left-pad-controversy-explained-2016-3)). They could continue to maintain their own private version as well -- perhaps as a testing ground for new ideas -- but the community package would be deployed from the community repo and would require a PR to update. This would give relevant folks a chance to review/comment.

**Comment by mvila** [comment]
I also think that usage is an important factor, but sometimes there are excellent projects that are not popular at all.

I think we need to establish very simple and programmable rules (like NumberOfUsersWithWriteAccess >= 3), and for the rest, let the community decide with a voting system.

About repos' control, I haven't thought about that yet, but my hunch is that Resdir shouldn't be coupled to GitHub (or whatever).

**Comment by hulkish** [comment]
I understand the argument for isolation from npm for this. I get it. But, I guess it would be awesome if you somehow had a way for resource packages to also be consumed  via npm.

**Comment by mvila** [comment]
@hulkish: Sure, but a developer wishing to wrap a tool published on npm in a resource has to write a resource definition anyway. That's the complicated part. Once that's done, it seems not a big deal to me to invoke "run publish" to publish on Resdir. But maybe I'm wrong, what do you think?

**Comment by hulkish** [comment]
The other thing to consider here is the conundrum of dependency duplication. What if you want to uae lodash in your resource - and your package.json. Same challenge as bower really. I am wondering what the plan is for this use case?

**Comment by mvila** [comment]
In case a resource wraps a tool published on npm, it will just define this tool as a dependency. It does not need to duplicate the tool's internal dependencies. For example, here is a simple resource wrapping `node-notifier `:

https://github.com/resdir/resdir/tree/master/resources/tool/notifier

I think you cannot compare a Bower manifest and a resource definition, these are different things.
